### PR TITLE
change: switch LICENSE from GPL3.0 to MIT for commercial purposes.

### PR DESCRIPTION
**Pull request by airscripts**
Hi Russell.

I've opened this PR in order to ask to you if are you willing to update your LICENSE file from GPL3.0 to MIT to make pyDMNrules as open as possible in terms of commerciality and usage.

Let me know if you're willing to update it.
Thanks for your contribute.

### CODE REVIEW

**Comment by russellmcdonell** [comment]
Can you explain the difference, and any commercial restrictions with GPL3.0?


Russell McDonell

**Comment by Airscripts** [comment]
Sure. Thanks in advance for your time.

Since GPL-3.0 is a copyleft license, everyone using pyDMNrules has to use the same identical license.
Moreover the source code has to be disclosed.

With MIT license, the one I'm proposing to you: you're completely free to keep software using pyDMNrules closed or open or even to keep the same license or change it.

It would be really useful for the closed source projects that want implement it.

**Comment by Airscripts** [comment]
Any update on this @russellmcdonell?

**Comment by russellmcdonell** [comment]
Yes, I have thought about this long and hard. Firstly Python itself is sort of GPL like licensed.
Then there's the module pyDMNrules uses, such as pySFeel and SLY and there's no point in making pyDMNrules incompatible with those licenses. I guess, more importantly, is the fact that pyDMNrules isn't meant to be commercial. It's meant to be an "introduction to DMN" for beginners. There's no optimization, so it will be slow. People were supposed to play with pyDMNrules and the transition to one of the commercial products like OpenRules.
HOWEVER, my main concern was respect for David Beasley who wrote SLY, without which this project would never have got off the ground. And the SLY license is MIT like. And I wrote pySFeel, so I have changed the licenses on both pySFeel and pyDMNrules to an MIT like license - basically do what you want, just don't mention my name.

**Comment by airscripts** [comment]
My deepest gratitude for this change and also for the time you gave me for the detailed explanation.

**Pull request closed without merging**
